name: Hello World Docker CI
on:
  push:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@cmspaixao'

      - name: Output time set in the container
        run: echo ${{ steps.hello-action.outputs.time }}
